<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Report_mdl extends CI_Model 
{
		
	function Report_mdl()
	{
		parent::__construct();			
	}		
			
	function to_excel($title, $sheet_title, $col, $data)
	{	
		if(ini_get('zlib.output_compression')) 
		{ 
			ini_set('zlib.output_compression', 'Off');	
		}			
		$this->load->helper('download');
		$this->load->library('excel');
		$col_name = array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z');
		$this->excel->getProperties()
				->setCreator("Generated by ISTS E-Logistic Information System")
				->setLastModifiedBy("ISTS E-Logistic System")
				->setTitle(sprintf("%s", $title))
				->setSubject("ACS Aerofood")				
				->setDescription(sprintf("%s", $title));				
		
		$this->excel->setActiveSheetIndex(0);		
		$this->excel->getActiveSheet()->setTitle(sprintf('%s', $sheet_title));
		$this->excel->getActiveSheet()->setCellValue('A1', sprintf('%s', $title));
		$this->excel->getActiveSheet()->setCellValue('A2', sprintf('Generated by Floating Equipment Monitoring System (FEMS). Creation Date: %s', date('d-m-Y H:i:s')));
		$this->excel->getActiveSheet()->getStyle('A1')->getFont()->setSize(14);
		$start_rows = 4;
		$col_i = 0;
		foreach($col as $k=>$v)
		{
			$this->excel->getActiveSheet()->setCellValue(sprintf('%s%d', $col_name[$col_i], $start_rows), sprintf("%s", $v));
			$this->excel->getActiveSheet()->getStyle(sprintf('%s%d', $col_name[$col_i], $start_rows))->getFont()->setBold(true);
			$col_i++;
		}
		$j=5;
		foreach($data as $kval)
		{
			$col_j = 0;
			foreach($col as $kk=>$vv)
			{
				$this->excel->getActiveSheet()->setCellValue(sprintf('%s%d', $col_name[$col_j], $j), sprintf('%s', $kval[$kk]));
				$col_j++;
			}
			$j++;
		}
		ob_end_clean();
		$fn = sprintf("%s-%s.xlsx", str_replace(array(" ","/"),"_", $title), date("dmY")); 
		$filename = APPPATH . sprintf("../assets/docs/%s", $fn);
		$objWriter = PHPExcel_IOFactory::createWriter($this->excel, 'Excel2007'); 		
		$objWriter->save($filename);				
		force_download($fn, file_get_contents($filename));			
		ob_end_clean();			
	}
		
}
	
?>
